server:
  port: 8080

spring:

  config:
    import: configserver:http://localhost:9271

  application:
    name: API-GATEWAY

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

      discovery:
        location:
          enable: true

      routes:
        - id: AUTH-SERVER
          uri: lb://AUTH-SERVER
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - AuthenticationFilter

        - id: BOOKING-SERVICE
          uri: lb://BOOKING-SERVICE
#          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/booking-service/**
          filters:
            - AuthenticationFilter

        - id: BUS-SERVICE
          uri: lb://BUS-SERVICE
#          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/bus-service/**
          filters:
            - AuthenticationFilter

        - id: PAYMENT-SERVICE
          uri: lb://PAYMENT-SERVICE
#          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/payment-service/**
          filters:
            - AuthenticationFilter

        - id: MAIL-SERVICE
          uri: lb://MAIL-SERVICE
#          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/mail-service/**
          filters:
            - AuthenticationFilter

managements:
  endpoints:
    web:
      exposure:
        include: "*"
